"""Explainer Agent — generates human-readable explanations (novelty #5).

Turns the run's decision traces, review findings, verification outcome and
rollback status into a Markdown narrative a human operator can read and audit.
"""

from __future__ import annotations

from cloud_orchestra.agents.base import BaseAgent
from cloud_orchestra.core.tracing import DecisionTrace
from cloud_orchestra.schemas import (
    Alert,
    ReviewResult,
    RollbackResult,
    Run,
    SecurityFinding,
    TerraformPlan,
    VerificationResult,
)


class ExplainerAgent(BaseAgent):
    name = "explainer"

    async def explain(
        self,
        run: Run,
        alert: Alert,
        traces: list[DecisionTrace],
        review: ReviewResult | None,
        plan: TerraformPlan | None,
        verification: VerificationResult | None,
        *,
        rollback: RollbackResult | None = None,
        findings: list[SecurityFinding] | None = None,
    ) -> str:
        lines: list[str] = []
        lines.append(f"# Remediation Explanation — run `{run.id}`")
        lines.append("")
        lines.append(f"**Alert:** {alert.name} (`{alert.severity.value}`) on "
                     f"{alert.resource_id} ({alert.resource_type}).")
        lines.append("")

        provider = plan.provider.value if plan else run.provider.value if run.provider else "n/a"
        lines.append(f"**Selected provider:** `{provider}`")
        if plan:
            lines.append(f"**Estimated cost:** ${plan.estimated_monthly_cost_usd:.2f}/month")

        detected = findings if findings is not None else (review.findings if review else [])
        lines.append("")
        lines.append("## Security & Cost Review")
        if review:
            lines.append(f"Final verdict: **{review.verdict.value}**. {review.summary}")
        if detected:
            lines.append(f"{len(detected)} finding(s) detected and remediated:")
            for finding in detected:
                source = "red-team" if finding.found_by_red_team else "review"
                lines.append(
                    f"- `[{finding.severity.value.upper()}]` **{finding.vulnerability_type}** "
                    f"({source}, CVSS {finding.cvss_score:.1f}): {finding.description}"
                )
        else:
            lines.append("No security findings were detected.")

        if verification:
            lines.append("")
            lines.append("## Verification")
            lines.append(verification.explanation)
            lines.append(f"Resolution status: **{verification.comparison.value}**.")

        if rollback is not None:
            lines.append("")
            lines.append("## Rollback")
            outcome = "reverted successfully" if rollback.succeeded else "FAILED to revert"
            lines.append(f"The remediation was {outcome} "
                         f"({len(rollback.reverted_resources)} resource(s)).")

        lines.append("")
        lines.append("## Decision Trace")
        for trace in traces:
            lines.append(f"- **{trace.agent}** / `{trace.step}`: {trace.rationale or trace.output_summary}")

        lines.append("")
        lines.append("---")
        lines.append("*Generated by the Cloud-Orchestra Explainer Agent.*")
        return "\n".join(lines)
